FakirCms.WebUI/Areas/Admin/Controllers/HaberCategoryController.cs
using FakirCms.Domain.Entities;
using FakirCms.Domain.Services;
using FakirCms.WebUI.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FakirCms.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class HaberCategoryController : Controller
    {
        private IHaberCategoryService _haberCategoryService;
        public HaberCategoryController(IHaberCategoryService haberCategoryService)
        {
            _haberCategoryService = haberCategoryService;
        }
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetData()
        {
            var resultData=(from category in _haberCategoryService.items
                                orderby category.Id descending
                                select new{
                                    Id=category.Id,
                                    Title=category.Title,
                                    Author=category.CreatedBy.Name,
                                    Date=category.Created.ToString("yyyy/MM/dd")
                                }).ToArray();
            return Json(new { data = resultData }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            CreateHaberCategoryModel model = new CreateHaberCategoryModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateHaberCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id > 0)
                {
                    //make a update
                    HaberCategory category = _haberCategoryService.FindById(model.Id);
                    category.Title = model.Title;
                    category.Alias = model.Alias;
                    category.Description = model.Description;
                    category.Tags = model.Tags;
                    var result = _haberCategoryService.Update(category);
                    if (result)
                    {
                        TempData["success"] = "Haber Kategorisi başarılı bir şekilde güncellendi";
                    }
                    else
                    {
                        TempData["error"] = "Haber Kategorisi güncellenirken bir hatayla karşılaşıldı";
                    }
                }
                else
                {
                    HaberCategory category = new HaberCategory();
                    category.Title = model.Title;
                    category.Alias = model.Alias;
                    category.Description = model.Description;
                    category.Tags = model.Tags;

                    var result = _haberCategoryService.Create(category);
                    if (result)
                    {
                        TempData["success"] = "Haber Kategorisi başarılı bir şekilde eklendi";
                    }
                    else
                    {
                        TempData["error"] = "Haber Kategorisi eklenirken bir hatayla karşılaşıldı";
                    }
                }
                return View(model);
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            HaberCategory category = _haberCategoryService.FindById(id);
            if (category == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            else
            {
                CreateHaberCategoryModel model = new CreateHaberCategoryModel()
                {
                    Id = category.Id,
                    Alias = category.Alias,
                    Title = category.Title,
                    Description=category.Description,
                    Tags=category.Tags,
                    Created=category.Created,
                    Updated=category.Updated,
                    CreatedByName=category.CreatedBy.Name,
                    UpdatedByName=category.UpdatedBy.Name
                };
                return View("Create", model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Delete(int id)
        {
            HaberCategory category = _haberCategoryService.FindById(id);
            if (category == null)
            {
                return Json(new { success = false, msg = string.Format("The {0} id'ye sahip haber kategorisi bulunamadı", id) }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //delete aciklama
                _haberCategoryService.Delete(id);
                return Json(new { success = true, msg = "Başarılı bir şekilde silme işlemi gerçekleşti" }, JsonRequestBehavior.AllowGet);
            }
        }

	}
}

FakirCms.WebUI/Areas/Admin/Views/HaberCategory/Create.cshtml
@model FakirCms.WebUI.Areas.Admin.Models.CreateHaberCategoryModel
@{
    ViewBag.Title = "Haber Kategori";
}

@section Scripts{
    <script src="~/Areas/Admin/Scripts/pages/HaberCategoryCreateView.js"></script>

    <script type="text/javascript">
        $(function () {

            $("#habercategorycreateview").HaberCategoryCreateView();
        });
    </script>

}

@section ContentHeader{
    <h1>
        Kategori:
        @if (Model.Id > 0)
        {
            <small>Düzenle</small>
        }
        else
        {
            <small>Yeni</small>
        }

    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="@Url.Action("Index","HaberCategory")">Kategoriler</a></li>
        @if (Model.Id > 0)
        {
            <li class="active">Kategori Düzenle</li> }
        else
        {
            <li class="active">Yeni Kategori</li>}

    </ol>
}



<div id="habercategorycreateview">
    @using (Html.BeginForm("Create", "HaberCategory", FormMethod.Post, new { @class = "role", @id = "AdminForm" }))
    {

        <div id="ShowResultDiv" style="display: block;">
            @if (TempData["success"] != null)
            {
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @TempData["success"]
            </div>
            }

            @if (TempData["error"] != null)
            {
            <div class="alert alert-error">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @TempData["error"]
            </div>
            }

            @if (!ViewData.ModelState.IsValid)
            {
            <div class='alert alert-danger alert-dismissable'>
                <i class='fa fa-ban'></i>
                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>
                @Html.ValidationSummary()
            </div>
            }
        </div>
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)
        <div class="row">
            <div class="col-md-9">
                <!-- Custom Nav Tabs Start-->
                <div class="nav-tabs-custom">
                    <div class="box">
                        <div class="box-header">
                            <h3>Kategori Özellikleri</h3>
                        </div>
                        <!--Box Body Start-->
                        <div class="box-body">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Alias, new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(m => m.Alias, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Tags, new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(m => m.Tags, new { @class = "form-control", @data_role = "tagsinput" })
                                    </div>
                                </div>
                            </div>
                            <!--Form Horizontal End-->
                        </div>
                        <!-- Box Body End-->
                        <!--Box Footer Start-->
                        <div class="box-footer">
                            <div class="form-group">

                                <input type="submit" value="Kaydet" class="btn btn-default" />
                                @Html.ActionLink("İptal", "Index")

                            </div>
                        </div>
                        <!-- Box Footer End-->
                    </div>
                    <!--Box Body End-->
                </div>
                <!-- Custom Nav Tabs End-->
            </div>
            <div class="col-md-3">
                <div class="box box-solid">
                    <div class="box-header">
                        <h3 class="box-title">Kategori Bilgisi</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                        </div><!-- /.box-tools -->
                    </div>
                    <div class="box-body" style="font-size:13px">
                        <div class="row">
                            @Html.Label("Kayıt Tarihi:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.Created.ToString(string.Format("d MMMM yyyy hh:mm"))
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Oluşturan:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.CreatedByName
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Güncellenme Tarihi:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.Updated.ToString(string.Format("d MMMM yyyy hh:mm"))
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Güncelleyen:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.UpdatedByName
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Kimlik:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.Id
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

FakirCms.WebUI/Areas/Admin/Views/HaberCategory/Index.cshtml
@{
    ViewBag.Title = "Haber Kategorileri";
}

@section ContentHeader{
    <h1>
        Haber Kategori Yöneticisi
        <small>Kategoriler</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Anasayfa</a></li>
        <li class="active">Haber Kategorileri</li>
    </ol>
}




<div id="habercategoryindexview">

    <div id="ShowResultDiv" style="display: block;">
        @if (TempData["success"] != null)
        {
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @TempData["success"]
            </div>
        }

        @if (TempData["error"] != null)
        {
            <div class="alert alert-error">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @TempData["error"]
            </div>
        }
    </div>

    @Html.AntiForgeryToken()
    <div class="box">
        <!-- Box Header Start -->
        <div class="box-header">
            <a class="toolbar" href="@Url.Action("Create","HaberCategory")">
                <i class="icon-32-new"></i>Yeni Kategori
            </a>
            <a class="toolbar taskEvent" href="" data-task="exit" data-ajax="false" data-checkcontrol="false" data-showresultinpopup="false">
                <i class="icon-32-cancel"></i>Çıkış
            </a>
        </div>
        <!-- Box Header End -->
        <!-- Box Body Start-->
        <div class="box-body">

            <table id="AdminTable" class="table table-striped table-bordered dataTable"></table>
        </div>
        <!-- Box Body End-->
        <!-- Box Footer Start-->
        <div class="box-footer clearfix">

        </div>
        <!-- Box Footer End -->
    </div>
</div>

@section Css{
    <link href="@Url.Content("~/Areas/Admin/Content/css/datatables/dataTables.bootstrap.css")" rel="stylesheet" type="text/css">
}

@section Scripts{

    <script src="~/Areas/Admin/Scripts/pages/HaberCategoryIndexView.js"></script>
    <script type="text/javascript">
        $("#habercategoryindexview").HaberCategoryIndexView({
            tableId: "AdminTable",
            controller: "HaberCategory"
        });
    </script>
}