FakirCms.WebUI/Areas/Admin/Models/AuthorViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakirCms.WebUI.Areas.Admin.Models
{
    public class CreateAuthorModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Yazar adını giriniz")]
        [Display(Name = "Yazar Adı")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Takma ismi giriniz")]
        [Display(Name = "Takma İsim")]
        public string Alias { get; set; }
        [Required(ErrorMessage = "Tanıtım Metnini giriniz")]
        [Display(Name = "Tanıtım Metni")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required(ErrorMessage = "Resim Seçin")]
        [DataType(DataType.ImageUrl)]
        [Display(Name = "Resim Seç:")]
        public string Image { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage="Email adresini giriniz")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Geçersiz email adresi")]
        public string Email { get; set; }
        
        //User updated created informations
        [DataType(DataType.DateTime)]
        [Display(Name = "Oluşturulma Tarihi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Created { get; set; }
        [Display(Name = "Yazar")]
        public string CreatedByName { get; set; }
        [Display(Name = "Düzenleyen")]
        public string UpdatedByName { get; set; }
        [Display(Name = "Düzenleme Tarihi")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Updated { get; set; }

        //Seo
        [Display(Name = "Meta Başlık Etiketi")]
        [MaxLength(70, ErrorMessage = "Meta Başlık Etiketi maksimum 70 karakter uzunluğunda olmalı")]
        public string MetaTitle { get; set; }
        [Display(Name = "Meta Tanıtım Etiketi")]
        [MaxLength(160, ErrorMessage = "Meta Tanıtım Etiketi maksimum 160 karakter uzunluğunda olmalı")]
        public string MetaDescription { get; set; }
        [Display(Name = "Meta Anahtar Kelimeleri Giriniz")]
        public string MetaKeywords { get; set; }
    }
}

FakirCms.WebUI/Areas/Admin/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FakirCms.Domain;
using FakirCms.Domain.Entities;
using FakirCms.Domain.Services;
using FakirCms.WebUI.Areas.Admin.Models;
using System.Net;

namespace FakirCms.WebUI.Areas.Admin.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorService _authorService;
        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetData()
        {
            var resultData = (from author in _authorService.Items
                              orderby author.Id descending
                              select new
                              {
                                  Id=author.Id,
                                  Image=author.Image,
                                  Name=author.Name,
                                  Created = author.Created.ToString("yyyy/MM/dd"),
                                  Updated = author.Updated.ToString("yyyy/MM/dd")
                              }).ToArray();
            return Json(new { data = resultData }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            CreateAuthorModel model = new CreateAuthorModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateAuthorModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id > 0)
                {
                    //make a update
                    Author author = _authorService.FindById(model.Id);
                    author.Name = model.Name;
                    author.Image = model.Image;
                    author.Description = model.Description;
                    author.Email = model.Email;
                    author.Alias = model.Alias;
                    author.MetaDescription = model.MetaDescription;
                    author.MetaKeywords = model.MetaKeywords;
                    author.MetaTitle = model.MetaTitle;
                    var result = _authorService.Update(author);
                    if (result)
                    {
                        TempData["success"] = "Yazar başarılı bir şekilde güncellendi";
                    }
                    else
                    {
                        TempData["error"] = "Yazar güncellenirken bir hatayla karşılaşıldı";
                    }
                }
                else
                {
                    Author author = new Author();
                    author.Name = model.Name;
                    author.Image = model.Image;
                    author.Description = model.Description;
                    author.Email = model.Email;
                    author.Alias = model.Alias;
                    author.MetaDescription = model.MetaDescription;
                    author.MetaKeywords = model.MetaKeywords;
                    author.MetaTitle = model.MetaTitle;
                    var result = _authorService.Create(author);
                    if (result)
                    {
                        TempData["success"] = "Yazar başarılı bir şekilde eklendi";
                    }
                    else
                    {
                        TempData["error"] = "Yazar eklenirken bir hatayla karşılaşıldı";
                    }
                }
                return View(model);
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Author author = _authorService.FindById(id);
            if (author == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            CreateAuthorModel model = new CreateAuthorModel()
            {
                Id = author.Id,
                Alias = author.Alias,
                Name = author.Name,
                Description = author.Description,
                Image=author.Image,
                Email = author.Email,
                MetaTitle = author.MetaTitle,
                MetaDescription = author.MetaDescription,
                MetaKeywords = author.MetaKeywords,
                Created = author.Created,
                Updated = author.Updated,
                CreatedByName = author.CreatedBy.Name,
                UpdatedByName = author.UpdatedBy.Name
            };
            return View("Create", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Delete(int id)
        {
            Author author = _authorService.FindById(id);
            if (author == null)
            {
                return Json(new { success = false, msg = string.Format("The {0} id'ye sahip haber kategorisi bulunamadı", id) }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //delete author
                _authorService.Delete(id);
                return Json(new { success = true, msg = "Başarılı bir şekilde silme işlemi gerçekleşti" }, JsonRequestBehavior.AllowGet);
            }
        }
	}
}

FakirCms.WebUI/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FakirCms.Domain.Services;
using FakirCms.Domain.Entities;
using FakirCms.Domain.Models;

namespace FakirCms.WebUI.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorService _authorService;
        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }
        public ActionResult Index()
        {
            List<Author> authorlist = _authorService.Items.ToList();
            List<AuthorDetail> detailedAuthorList = _authorService.GetAuthorDetailList(authorlist); 

            return View(detailedAuthorList);
        }
	}
}

FakirCms.WebUI/Areas/Admin/Views/Author/Create.cshtml
@model FakirCms.WebUI.Areas.Admin.Models.CreateAuthorModel
@{
    ViewBag.Title = "Haber Kategori";
}

@section Scripts{
    <script src="~/Areas/Admin/Scripts/ImageBox.js"></script>
    <script src="~/Areas/Admin/Scripts/pages/AuthorCreateView.js"></script>

    <script type="text/javascript">
        $(function () {

            $("#authorcreateview").AuthorCreateView();
        });
    </script>

}

@section ContentHeader{
    <h1>
        Yazar:
        @if (Model.Id > 0)
        {
            <small>Düzenle</small>
        }
        else
        {
            <small>Yeni</small>
        }

    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="@Url.Action("Index","Author")">Yazarlar</a></li>
        @if (Model.Id > 0)
        {
            <li class="active">Yazar Düzenle</li> }
        else
        {
            <li class="active">Yeni Yazar</li>}

    </ol>
}



<div id="authorcreateview">
    @using (Html.BeginForm("Create", "Author", FormMethod.Post, new { @class = "role", @id = "AdminForm" }))
    {

        <div id="ShowResultDiv" style="display: block;">
            @if (TempData["success"] != null)
            {
                <div class="alert alert-success">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    @TempData["success"]
                </div>
            }

            @if (TempData["error"] != null)
            {
                <div class="alert alert-error">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    @TempData["error"]
                </div>
            }

            @if (!ViewData.ModelState.IsValid)
            {
                <div class='alert alert-danger alert-dismissable'>
                    <i class='fa fa-ban'></i>
                    <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>
                    @Html.ValidationSummary()
                </div>
            }
        </div>
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)
        <div class="row">
            <div class="col-md-9">
                <!-- Custom Nav Tabs Start-->
                <div class="nav-tabs-custom">
                    <div class="box">
                        <div class="box-header">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="active"><a href="#tab_1" data-toggle="tab">Yazar Özellikleri</a></li>
                                <li class=""><a href="#tab_2" data-toggle="tab">Meta</a></li>
                            </ul>
                        </div>
                        <!--Box Body Start-->
                        <div class="box-body">
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <!--Tab 1 Start -->
                                <div class="tab-pane active" id="tab_1">
                                    <div class="form-horizontal">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Alias, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(m => m.Alias, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Email, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                <div id="ImageBrowserContainer">
                                                    <div class="input-group">
                                                        @Html.TextBoxFor(model => model.Image, new { @class = "form-control" })
                                                        <span class="input-group-btn">
                                                            <button class="btn btn-default" id="btnAddImage" type="button">
                                                                Resim Ekle
                                                            </button>
                                                        </span>
                                                    </div>
                                                    <div id="image-preview">

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!--Form Horizontal End-->
                                </div>
                                <!--Tab 1 End-->
                                <!--Tab 2 Start-->
                                <div class="tab-pane" id="tab_2">
                                    <div class="form-horizontal">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.MetaTitle, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(m => m.MetaTitle, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.MetaDescription, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextAreaFor(m => m.MetaDescription, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.MetaKeywords, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(m => m.MetaKeywords, new { @class = "form-control", @data_role = "tagsinput" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--Tab2 End-->
                            </div>
                            <!--Tab Content End-->
                        </div>
                        <!-- Box Body End-->
                        <!--Box Footer Start-->
                        <div class="box-footer">
                            <div class="form-group">

                                <input type="submit" value="Kaydet" class="btn btn-default" />
                                @Html.ActionLink("İptal", "Index")

                            </div>
                        </div>
                        <!-- Box Footer End-->
                    </div>
                    <!--Box Body End-->
                </div>
                <!-- Custom Nav Tabs End-->
            </div>
            <div class="col-md-3">
                <div class="box box-solid">
                    <div class="box-header">
                        <h3 class="box-title">Yazar Bilgisi</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                        </div><!-- /.box-tools -->
                    </div>
                    <div class="box-body" style="font-size:13px">
                        <div class="row">
                            @Html.Label("Kayıt Tarihi:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.Created.ToString(string.Format("d MMMM yyyy hh:mm"))
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Oluşturan:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.CreatedByName
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Güncellenme Tarihi:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.Updated.ToString(string.Format("d MMMM yyyy hh:mm"))
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Güncelleyen:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.UpdatedByName
                            </div>
                        </div>
                        <div class="row">
                            @Html.Label("Kimlik:", new { @class = "col-md-6" })
                            <div class="col-md-6">
                                @Model.Id
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

FakirCms.WebUI/Areas/Admin/Views/Author/Index.cshtml
@{
    ViewBag.Title = "Yazarlar";
}

@section ContentHeader{
    <h1>
        Yazar Yöneticisi
        <small>Yazarlar</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Anasayfa</a></li>
        <li class="active">Yazarlar</li>
    </ol>
}




<div id="habercategoryindexview">

    <div id="ShowResultDiv" style="display: block;">
        @if (TempData["success"] != null)
        {
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @TempData["success"]
            </div>
        }

        @if (TempData["error"] != null)
        {
            <div class="alert alert-error">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @TempData["error"]
            </div>
        }
    </div>

    @Html.AntiForgeryToken()
    <div class="box">
        <!-- Box Header Start -->
        <div class="box-header">
            <a class="toolbar" href="@Url.Action("Create","Author")">
                <i class="icon-32-new"></i>Yeni Yazar
            </a>
            <a class="toolbar taskEvent" href="" data-task="exit" data-ajax="false" data-checkcontrol="false" data-showresultinpopup="false">
                <i class="icon-32-cancel"></i>Çıkış
            </a>
        </div>
        <!-- Box Header End -->
        <!-- Box Body Start-->
        <div class="box-body">

            <table id="AdminTable" class="table table-striped table-bordered dataTable"></table>
        </div>
        <!-- Box Body End-->
        <!-- Box Footer Start-->
        <div class="box-footer clearfix">

        </div>
        <!-- Box Footer End -->
    </div>
</div>

@section Css{
    <link href="@Url.Content("~/Areas/Admin/Content/css/datatables/dataTables.bootstrap.css")" rel="stylesheet" type="text/css">
}

@section Scripts{
    <script src="~/Areas/Admin/Scripts/pages/AuthorIndexView.js"></script>
    <script type="text/javascript">
        $("#habercategoryindexview").AuthorIndexView({
            tableId: "AdminTable",
            controller: "Author"
        });
    </script>
}