FakirCms.WebUI/Controllers/WidgetController.cs
using FakirCms.Domain.Entities;
using FakirCms.Domain.Models;
using FakirCms.Domain.Services;
using FakirCms.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakirCms.WebUI.Controllers
{
    public class WidgetController : Controller
    {
        private IHaberService _haberService;
        private IAuthorService _authorService;
        public WidgetController(IHaberService haberService,IAuthorService authorService)
        {
            _haberService = haberService;
            _authorService = authorService;
        }


        public PartialViewResult TopHabers()
        {
            List<Haber> popularHabers = _haberService.GetPopularHabers().Take(6).ToList();
            List<Haber> recentHabers = _haberService.GetRecentHabers().Take(6).ToList();
            PopularHaberModel model = new PopularHaberModel()
            {
                Popular=_haberService.GetHaberDetailList(popularHabers),
                Recent=_haberService.GetHaberDetailList(recentHabers)
            };
            return PartialView(model);
        }

        public PartialViewResult Authors()
        {
            List<Author> authors = _authorService.Items.Take(6).ToList();
            List<AuthorDetail> detailedAuthor = _authorService.GetAuthorDetailList(authors);

            return PartialView(detailedAuthor);
        }

	}
}

FakirCms.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]><html class="ie ie8"><![endif]-->
<!--[if IE 9]><html class="ie ie9"><![endif]-->
<!--[if gt IE 9]><!-->
<html xmlns:og="http://opengraphprotocol.org/schema/">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <!-- Title Tag -->
    <title>@ViewBag.Title</title>

    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    @RenderSection("Meta", false)


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Site Favicon -->
    <link rel="icon" href="/Content/images/favicon.ico" type="image/x-icon" />


    <!-- Web Fonts  -->
    <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700' rel='stylesheet' type='text/css'>

    <!-- Libs CSS -->
    <!-- font awesome -->
    @Styles.Render("~/content/css/font-awesome.min.css")
    <!-- magnific-popup -->
    @Styles.Render("~/content/css/magnific-popup.css")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.0.8/css/swiper.css" />
    <!-- Superfish Menu -->
    @Styles.Render("~/content/css/superfish")
    <!--Slick Nav Menu-->
    @Styles.Render("~/content/css/slicknav")
    <!-- social likes -->
    @Styles.Render("~/content/css/social-likes")


    <!-- Theme CSS -->
    @Styles.Render("~/content/css/themecss")
    <!-- Layout Css-->
    @Styles.Render("~/content/css/layout")
    <!-- custom -->
    @Styles.Render("~/content/css/custom")

    @RenderSection("Css",false)

    <!--[if IE 8]>
    <link href="assets/css/ie8.css" rel="stylesheet" type="text/css" />
    <![endif]-->

</head>
<body>
    <div class="body-wrapper full-width-mode boxed-mode">

        <div id="site-top-menu">
            <div class="container">
                <div class="row row-wrapper">
                    <div class="row">
                        <div id="top">
                            <div id="bugun">3 Ağustos 2015, Pazartesi | 10:10:02 </div>
                            <script type="text/javascript">
                                /* =========== Tarih ve Saat =========== */
                                function tarihsaat() { var b = new Date, g = b.getSeconds(), d = b.getMinutes(), a = b.getHours(), c = b.getDay(), h = b.getDate(), k = b.getMonth(), b = b.getFullYear(); 10 > a && (a = "0" + a); 10 > g && (g = "0" + g); 10 > d && (d = "0" + d); document.getElementById("bugun").innerHTML = h + " " + "Ocak Şubat Mart Nisan Mayıs Haziran Temmuz Ağustos Eylül Ekim Kasım Aralik".split(" ")[k] + " " + b + ", " + "Pazar Pazartesi Salı Çarsamba Perşembe Cuma Cumartesi".split(" ")[c] + " | " + a + ":" + d + ":" + g + " "; setTimeout("tarihsaat()", 1E3) } function CC_noErrors() { return !0 } window.onerror = CC_noErrors; function bookmarksite(b, g) { document.all ? window.external.AddFavorite(g, b) : window.sidebar && window.sidebar.addPanel(b, g, "") }
                                /* =========== Tarih ve Saat =========== */

                                tarihsaat();</script>


                            <div class="top-page">
                                <ul>
                                    <li style="border-right:1px solid #6e6e6e;"><a href="/" title="Ana Sayfa">Ana Sayfa</a></li>
                                    <li style="border-right:1px solid #6e6e6e;"><a href="/ilkelerimiz.html" title="İlkelerimiz">İlkelerimiz</a></li>
                                    <li style="border-right:1px solid #6e6e6e;"><a href="/kunye.html" title="Künye">Künye</a></li>
                                    <li style="border-right:1px solid #6e6e6e;"><a href="iletisim.html" title="İletisim">İletisim</a></li>
                                    <li style="border-right:1px solid #6e6e6e;"><a href="hakkimizda.html" title="Hakkımızda">Hakkımızda</a></li>
                                </ul>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <div class="container">
                <div class="row row-wrapper">
                    <div class="row">
                        <div class="bannerdiv">
                            <a href="/" title="Demo Haber Site">
                                <img src="@Url.Content("~/Content/images/logo.png")" alt="Demo Haber Site" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div id="site-main-menu">
            <div class="container">
                <div class="row row-wrapper">
                    <div class="row">
                        <div class="navigationdiv">
                            <ul id="navigation" class="sf-menu" style="display: block;">
                                <li>
                                    @Html.ActionLink("Anasayfa", "Index", "Home")
                                </li>
                                <li><a href="@Url.RouteUrl("HaberList",new{alias="gundem"})" title="Gündem">Gündem</a></li>
                                <li><a href="@Url.RouteUrl("HaberList", new { alias = "bilim" })" title="Bilim">Bilim</a>
                                <li><a href="@Url.RouteUrl("HaberList", new { alias = "kultur-sanat" })" title="Kültür Sanat">Kültür Sanat</a>
                                <li><a href="@Url.RouteUrl("HaberList",new{alias="dis-haberler"})" title="Dış Haberler">Dış Haberler</a></li>
                                <li><a href="@Url.RouteUrl("HaberList",new{alias="spor"})" title="Spor">Spor</a></li>
                                <li><a href="@Url.RouteUrl("AuthorList")" title="Yazarlar">Yazarlar</a></li>
                            </ul>
                            <div class="clearfix">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @RenderSection("TopHaber", false)

        <div class="content-wrapper">
            <div id="content" class="site-content">
                <div class="container">
                    <div class="row row-wrapper">
                        <div class="row">
                            <div id="primary" class="content-area eight columns">
                                @RenderBody()
                            </div><!-- #primary -->
                            <div id="secondary" class="widget-area four columns" role="complementary">

                                <!--Yazar Widget-->
                                @Html.Action("Authors", "Widget")
                                <!--Yazar Widget End-->
                                <!--TopHabers -->
                                @Html.Action("TopHabers", "Widget")
                                <!-- Top Habers End -->


                            </div><!-- #secondary -->
                        </div><!--.row -->
                    </div><!--.row-wrapper -->
                </div><!-- .container -->
            </div><!-- #content -->
        </div><!-- #content-wrapper -->
        <footer id="footer" class="site-footer" role="contentinfo">
            <div class="footer-copyright-wrapper">
                <div class="footer-copyright">
                    <div class="container">
                        <div class="copy-left center">
                            Haber Domo Site
                        </div>
                    </div>
                </div>
            </div>
        </footer><!-- #colophon -->
    </div><!-- END .body_wrapper -->
    <div id="fb-root"></div>
    <!-- jQuery -->
    <script src="/Scripts/plugins/jquery-1.11.1.min.js"></script>

    <!-- Head Libs -->
    <script src="~/Scripts/plugins/modernizr.custom.js"></script>
    <!-- jQuery UI -->
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <!-- flexslider -->
    <script src="/Scripts/plugins/jquery.flexslider.js"></script>
    <!-- carouFredSel -->
    <script src="/Scripts/plugins/owl.carousel.min.js"></script>
    <!-- progressbar -->
    <script src="/Scripts/plugins/jquery.countTo.js"></script>
    <!-- animated scroll loading effects -->
    <script src="/Scripts/plugins/viewportchecker.js"></script>
    <!-- popup -->
    <script src="/Scripts/plugins/jquery.magnific-popup.min.js"></script>
    <script src="/Scripts/plugins/zepto.js"></script>
    <!-- Superfish Menu -->
    <script src="/Scripts/plugins/hoverIntent.js"></script>
    @Scripts.Render("~/scripts/plugins/superfish")
    <!--Slick Nav Menu-->
    @Scripts.Render("~/scripts/plugins/slicknav")
    <!-- Social likes-->
    @Scripts.Render("~/scripts/plugins/social-likes")

    <!-- top menu -->
    @*<script src="/Scripts/plugins/topmenu.js"></script>*@
    <!-- mega menu -->
    @*
        <script src="/Scripts/plugins/superfish.js"></script>*@
    <!-- responsive video -->
    <script src="/Scripts/plugins/jquery.fitvids.js"></script>
    <!--swiper slider-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.0.8/js/swiper.jquery.min.js"></script>
    <!--Custom javascript-->
    <script src="/Scripts/plugins/custom.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-65959032-1', 'auto');
        ga('send', 'pageview');

    </script>

    @RenderSection("Scripts",false)

</body>
</html>